Fix error in pixbuf savev
I encounter error when I try to save the image from screenshot:
```
  File "/usr/lib/python3.14/site-packages/kazam/backend/grabber.py", line 167, in save
    self.pixbuf.savev(filename, "png", "", "")
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Unable to marshal str as an array, use .encode() to convert to bytes
```
The error is that empty string cannot be converted to an array.